GHCR image push
silinternational/mysql-backup-restore pull request #25
Opened 2024-10-04 08:13 UTC by Praveenraj-K

-Image will be pushed to DockerHub & GHCR
-updated the code so that it will only trigger when workflow trigger happens in the main branch

2024-10-04 11:37 UTC, devon-sil commented
Thanks.  I've added the developers for review.

2024-10-07 10:27 UTC, briskt requested changes
same comments as other repos

2024-10-07 10:27 UTC, briskt commented on .github/workflows/build-and-publish.yml
> +      - main
This should include `tags` as well

2024-10-07 10:27 UTC, briskt commented on .github/workflows/build-and-publish.yml
> +          tags: |
This should include `semver` or `type=ref,event=tag` as well.

2024-10-08 07:34 UTC, briskt approved these changes

2024-10-08 14:06 UTC, merged